version: '3.6'
services:
    api:
        build: .
        depends_on: 
            - db
        environment: 
            PORT: 5000
            SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:123@db/crudperson
        networks: 
            - default
        ports:
            - 5000:5000
        restart: always
    db:
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: crudperson
        image: postgres:latest
        networks: 
            - default
        ports:
            - 5432:5432
        restart: always
